const commonUserDefaults = {
  lastSpaceId: '',
  color: '#98d3ff',
  name: 'Admin',
  description: '',
  website: '',
  arenaAccessToken: '',
  favoriteUsers: [],
  favoriteSpaces: [],
  favoriteColors: [],
  hiddenSpaces: [],
  cardsCreatedCount: 0,
  cardsCreatedCountRaw: 0,
  isUpgraded: true,
  isModerator: false,
  filterShowUsers: false,
  filterShowDateUpdated: false,
  filterShowAbsoluteDates: false,
  filterUnchecked: false,
  filterComments: false,
  shouldHideTutorialCards: false,
  shouldHideDateCards: false,
  shouldEmailNotifications: false,
  shouldEmailBulletin: false,
  shouldEmailWeeklyReview: false,
  shouldShowMoreAlignOptions: false,
  shouldUseLastConnectionType: true,
  shouldShowItemActions: false,
  shouldShowMultipleSelectedLineActions: false,
  shouldShowMultipleSelectedBoxActions: false,
  shouldShowMultipleSelectedListActions: false,
  shouldShowCurrentSpaceTags: false,
  showInExploreUpdatedAt: null,
  defaultSpaceBackground: null,
  defaultSpaceBackgroundGradient: null,
  defaultSpaceBackgroundTint: null,
  defaultCardBackgroundColor: null,
  defaultConnectionControlPoint: 'q00,00',
  shouldUseStickyCards: true,
  shouldIncreaseUIContrast: false,
  shouldPauseConnectionDirections: false,
  shouldInvertZoom: false,
  lastUsedImagePickerService: '',
  theme: null,
  themeIsSystem: true,
  outsideSpaceBackgroundIsStatic: false,
  shouldDisableHapticFeedback: false,
  isDebugMode: false,
  studentDiscountIsAvailable: false,
  lastSidebarSection: '',
  prevInviteEmails: '',
  prevHeaderFontId: 0,
  cardSettingsShiftEnterShouldAddChildCard: true,
  cardSettingsCardWrapWidth: 200,
  prevSettingsSection: null,
  disabledKeyboardShortcuts: ['newSpace'],
  shouldShowMinimapJumpToList: true,
  cardDetailsResizeWidth: null,
  downgradeAt: null,
  appleAppAccountToken: null,
  appleSubscriptionIsActive: null,
  stripePlanIsPurchased: null,
  stripeSubscriptionId: null,
  dialogSpaceFilterByGroup: {},
  dialogSpaceFilterByUser: {},
  dialogSpaceFilterShowHidden: false,
  dialogSpaceFilterSortBy: null,
  dialogSpaceFilterByTemplates: false,
  tags: [],
  drawingBrushSize: 'm',
  drawingColor: null
}

export const createDefaultUserData = ({ id, email, apiKey }) => {
  return {
    id,
    email,
    apiKey,
    ...commonUserDefaults
  }
}

export const emojiPayload = {
  version: 'selfhost-v1',
  emojis: [
    { emoji: '??', name: 'grinning face', group: 'smileys' },
    { emoji: '??', name: 'slightly smiling face', group: 'smileys' },
    { emoji: '??', name: 'face with tears of joy', group: 'smileys' },
    { emoji: '??', name: 'smiling face with heart-eyes', group: 'smileys' },
    { emoji: '??', name: 'thinking face', group: 'smileys' },
    { emoji: '??', name: 'fire', group: 'symbols' },
    { emoji: '?', name: 'sparkles', group: 'symbols' },
    { emoji: '?', name: 'check mark button', group: 'symbols' },
    { emoji: '??', name: 'pushpin', group: 'objects' },
    { emoji: '??', name: 'paperclip', group: 'objects' },
    { emoji: '??', name: 'memo', group: 'objects' },
    { emoji: '??', name: 'books', group: 'objects' },
    { emoji: '??', name: 'direct hit', group: 'activities' },
    { emoji: '??', name: 'light bulb', group: 'objects' },
    { emoji: '??', name: 'rocket', group: 'travel' },
    { emoji: '??', name: 'seedling', group: 'nature' },
    { emoji: '??', name: 'rainbow', group: 'nature' },
    { emoji: '??', name: 'musical note', group: 'objects' },
    { emoji: '??', name: 'link', group: 'objects' },
    { emoji: '??', name: 'red heart', group: 'symbols' }
  ]
}
